[package]
name = "windowstest"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[dependencies]
windows = "0.11.0"

[build-dependencies]
windows = "0.11.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
panic = 'abort'
